apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synthetic-puzzle-output
  namespace: synthetic-puzzles
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
