from __future__ import annotations

import hashlib
import json
import random
import re
from pathlib import Path
from typing import Any, Callable

from .models import PuzzleRecord, Scenario


Cell = tuple[int, int]
Rectangle = dict[str, str]
Bounds = tuple[int, int, int, int]

_CELL_PATTERN = re.compile(r"^r([1-9][0-9]*)c([1-9][0-9]*)$", re.IGNORECASE)
_TRANSFORMATIONS = (
    "identity",
    "rotate_90",
    "rotate_180",
    "rotate_270",
    "reflect_horizontal",
    "reflect_vertical",
    "transpose",
    "anti_transpose",
)
_DIFFICULTY_SPECS = {
    "easy": (5, 5, 10, ["single_rectangle", "forced_area"]),
    "medium": (6, 6, 11, ["rectangle_candidates", "cell_ownership"]),
    "hard": (7, 7, 12, ["exact_cover", "overlap_elimination"]),
    "expert": (8, 8, 13, ["constraint_propagation", "multi_rectangle_interaction"]),
}


def format_cell(row: int, col: int) -> str:
    """Return the pipeline's one-based cell notation for a zero-based coordinate."""

    return f"r{row + 1}c{col + 1}"


def parse_cell(cell: str) -> Cell:
    """Parse an ``rNcM`` cell label into a zero-based coordinate."""

    match = _CELL_PATTERN.fullmatch(str(cell))
    if not match:
        raise ValueError(f"Invalid cell label: {cell!r}")
    return int(match.group(1)) - 1, int(match.group(2)) - 1


def _cell_sort_key(cell: str) -> tuple[int, int, str]:
    try:
        row, col = parse_cell(cell)
        return row, col, ""
    except (TypeError, ValueError):
        return 10**9, 10**9, str(cell)


def _normalized_clues(clues: list[dict[str, Any]]) -> list[dict[str, Any]]:
    normalized: list[dict[str, Any]] = []
    for clue in clues:
        if isinstance(clue, dict):
            raw_cell = clue.get("cell")
            try:
                cell = format_cell(*parse_cell(str(raw_cell)))
            except (TypeError, ValueError):
                cell = str(raw_cell) if raw_cell is not None else ""
            normalized.append({"cell": cell, "value": clue.get("value")})
        else:
            # Keeping malformed entries serializable lets structural validation
            # describe the problem instead of making canonicalization fail.
            normalized.append({"cell": "", "value": None})
    return sorted(
        normalized,
        key=lambda clue: (*_cell_sort_key(str(clue.get("cell", ""))), repr(clue.get("value"))),
    )


def canonical_puzzle(height: int, width: int, clues: list[dict[str, Any]]) -> str:
    """Serialize a Shikaku puzzle in its stable, compact representation."""

    payload = {"height": height, "width": width, "clues": _normalized_clues(clues)}
    return json.dumps(payload, separators=(",", ":"), sort_keys=True)


def parse_puzzle(puzzle: str) -> tuple[int, int, list[dict[str, Any]]]:
    payload = json.loads(puzzle)
    return int(payload["height"]), int(payload["width"]), list(payload["clues"])


def _is_plain_int(value: Any) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def validate_structure(
    height: int,
    width: int,
    clues: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Return structural clue errors without attempting a search.

    Two-by-two boards are accepted because they provide small, exact fixtures for
    the unsolvable and ambiguous pipeline edge cases. Production puzzles use the
    5x5 through 8x8 sizes generated by :class:`ShikakuPuzzleManager`.
    """

    violations: list[dict[str, Any]] = []
    dimensions_valid = (
        _is_plain_int(height)
        and _is_plain_int(width)
        and 2 <= height <= 15
        and 2 <= width <= 15
    )
    if not dimensions_valid:
        violations.append({"type": "grid_size", "height": height, "width": width})
    if not isinstance(clues, list):
        return violations + [{"type": "clues_type", "actual": type(clues).__name__}]
    if not clues:
        violations.append({"type": "missing_clues"})

    seen: dict[str, int] = {}
    total = 0
    values_valid = True
    for index, clue in enumerate(clues):
        if not isinstance(clue, dict):
            violations.append({"type": "clue_type", "index": index + 1})
            values_valid = False
            continue
        raw_cell = clue.get("cell")
        try:
            row, col = parse_cell(str(raw_cell))
            cell = format_cell(row, col)
        except (TypeError, ValueError):
            violations.append({"type": "cell_format", "index": index + 1, "cell": raw_cell})
            cell = None
            row = col = -1
        if cell is not None:
            if dimensions_valid and not (0 <= row < height and 0 <= col < width):
                violations.append({"type": "cell_bounds", "index": index + 1, "cell": cell})
            if cell in seen:
                violations.append(
                    {
                        "type": "duplicate_clue_cell",
                        "cell": cell,
                        "indices": [seen[cell], index + 1],
                    }
                )
            else:
                seen[cell] = index + 1

        value = clue.get("value")
        if not _is_plain_int(value) or value <= 0:
            violations.append(
                {"type": "clue_value", "index": index + 1, "cell": cell, "value": value}
            )
            values_valid = False
        else:
            total += value
            if dimensions_valid and value > height * width:
                violations.append(
                    {
                        "type": "clue_area",
                        "index": index + 1,
                        "cell": cell,
                        "value": value,
                        "maximum": height * width,
                    }
                )

    if dimensions_valid and values_valid and total != height * width:
        violations.append(
            {
                "type": "clue_area_total",
                "expected": height * width,
                "actual": total,
            }
        )
    return violations


def _rectangle(top: int, left: int, bottom: int, right: int, clue_cell: str) -> Rectangle:
    return {
        "clue_cell": clue_cell,
        "top_left": format_cell(top, left),
        "bottom_right": format_cell(bottom, right),
    }


def _rectangle_bounds(rectangle: dict[str, Any]) -> Bounds:
    top, left = parse_cell(str(rectangle["top_left"]))
    bottom, right = parse_cell(str(rectangle["bottom_right"]))
    return top, left, bottom, right


def _bounds_cells(bounds: Bounds) -> frozenset[Cell]:
    top, left, bottom, right = bounds
    return frozenset(
        (row, col)
        for row in range(top, bottom + 1)
        for col in range(left, right + 1)
    )


def _candidates_for_clue(
    height: int,
    width: int,
    clues: list[dict[str, Any]],
    selected_index: int,
) -> list[Rectangle]:
    clue = clues[selected_index]
    clue_cell = format_cell(*parse_cell(str(clue["cell"])))
    clue_row, clue_col = parse_cell(clue_cell)
    area = int(clue["value"])
    other_clues = {
        parse_cell(str(other["cell"]))
        for index, other in enumerate(clues)
        if index != selected_index
    }
    candidates: list[Rectangle] = []
    for rectangle_height in range(1, area + 1):
        if area % rectangle_height:
            continue
        rectangle_width = area // rectangle_height
        if rectangle_height > height or rectangle_width > width:
            continue
        first_top = max(0, clue_row - rectangle_height + 1)
        last_top = min(clue_row, height - rectangle_height)
        first_left = max(0, clue_col - rectangle_width + 1)
        last_left = min(clue_col, width - rectangle_width)
        for top in range(first_top, last_top + 1):
            bottom = top + rectangle_height - 1
            for left in range(first_left, last_left + 1):
                right = left + rectangle_width - 1
                cells = _bounds_cells((top, left, bottom, right))
                if cells & other_clues:
                    continue
                candidates.append(_rectangle(top, left, bottom, right, clue_cell))
    return sorted(
        candidates,
        key=lambda item: (*parse_cell(item["top_left"]), *parse_cell(item["bottom_right"])),
    )


def rectangle_candidates(
    height: int,
    width: int,
    clues: list[dict[str, Any]] | dict[str, Any],
    clue: dict[str, Any] | str | list[dict[str, Any]] | None = None,
) -> dict[str, list[Rectangle]] | list[Rectangle]:
    """Enumerate every legal clue rectangle.

    With no ``clue`` argument, the result maps each clue cell to its complete
    candidate list. Supplying a clue dict or cell label returns just that list.
    For compatibility with callers that naturally pass ``(clue, all_clues)``,
    that argument order is also accepted.
    """

    return_single = isinstance(clues, dict)
    if isinstance(clues, dict) and isinstance(clue, list):
        clues, clue = clue, clues
        return_single = True
    elif isinstance(clues, dict):
        single_clue = clues
        clues = [single_clue]
        clue = single_clue if clue is None else clue

    clue_list = list(clues)
    if validate_structure(height, width, clue_list):
        return [] if clue is not None or return_single else {}
    result = {
        str(item["cell"]): _candidates_for_clue(height, width, clue_list, index)
        for index, item in enumerate(clue_list)
    }
    if clue is None and not return_single:
        return result
    selected_cell = str(clue.get("cell")) if isinstance(clue, dict) else str(clue)
    try:
        selected_cell = format_cell(*parse_cell(selected_cell))
    except ValueError:
        return []
    return result.get(selected_cell, [])


def _prepared_candidates(
    height: int,
    width: int,
    clues: list[dict[str, Any]],
) -> dict[str, list[tuple[Rectangle, frozenset[Cell]]]]:
    by_clue = rectangle_candidates(height, width, clues)
    assert isinstance(by_clue, dict)
    return {
        cell: [(rectangle, _bounds_cells(_rectangle_bounds(rectangle))) for rectangle in rectangles]
        for cell, rectangles in by_clue.items()
    }


def solve_shikaku(
    height: int,
    width: int,
    clues: list[dict[str, Any]],
    limit: int = 2,
) -> list[list[Rectangle]]:
    """Solve by MRV exact cover and return at most ``limit`` rectangle tilings."""

    if limit <= 0 or validate_structure(height, width, clues):
        return []
    prepared = _prepared_candidates(height, width, clues)
    if any(not candidates for candidates in prepared.values()):
        return []

    all_cells = frozenset((row, col) for row in range(height) for col in range(width))
    clue_order = sorted(prepared, key=_cell_sort_key)
    solutions: list[list[Rectangle]] = []
    selected: dict[str, Rectangle] = {}

    def search(remaining: tuple[str, ...], occupied: frozenset[Cell]) -> None:
        if len(solutions) >= limit:
            return
        if not remaining:
            if occupied == all_cells:
                solutions.append([dict(selected[cell]) for cell in clue_order])
            return

        viable_by_clue: dict[str, list[tuple[Rectangle, frozenset[Cell]]]] = {}
        for clue_cell in remaining:
            viable = [candidate for candidate in prepared[clue_cell] if not candidate[1] & occupied]
            if not viable:
                return
            viable_by_clue[clue_cell] = viable

        # Every uncovered cell must still occur in at least one candidate of an
        # unassigned clue. This inexpensive exact-cover check prunes dead ends
        # before branching and keeps 8x8 generation quick.
        coverable = frozenset().union(
            *(cells for viable in viable_by_clue.values() for _, cells in viable)
        )
        if not all_cells - occupied <= coverable:
            return

        clue_cell = min(
            remaining,
            key=lambda cell: (len(viable_by_clue[cell]), _cell_sort_key(cell)),
        )
        next_remaining = tuple(cell for cell in remaining if cell != clue_cell)
        for rectangle, cells in viable_by_clue[clue_cell]:
            selected[clue_cell] = rectangle
            search(next_remaining, occupied | cells)
            selected.pop(clue_cell, None)
            if len(solutions) >= limit:
                return

    search(tuple(clue_order), frozenset())
    return solutions


def _coerce_rectangles(rectangles: Any) -> list[dict[str, Any]] | None:
    if isinstance(rectangles, str):
        try:
            rectangles = json.loads(rectangles)
        except (TypeError, json.JSONDecodeError):
            return None
    return rectangles if isinstance(rectangles, list) else None


def solution_violations(
    height: int,
    width: int,
    clues: list[dict[str, Any]],
    rectangles: list[dict[str, Any]] | str,
) -> list[dict[str, Any]]:
    """Validate a proposed rectangle tiling independently of the solver."""

    parsed_rectangles = _coerce_rectangles(rectangles)
    if parsed_rectangles is None:
        return [{"type": "solution_format"}]
    violations: list[dict[str, Any]] = []
    clue_values = {str(clue.get("cell")): clue.get("value") for clue in clues if isinstance(clue, dict)}
    clue_positions: dict[str, Cell] = {}
    for cell in clue_values:
        try:
            normalized = format_cell(*parse_cell(cell))
            clue_positions[normalized] = parse_cell(normalized)
        except ValueError:
            continue

    seen_clues: dict[str, int] = {}
    occupied: dict[Cell, str] = {}
    for index, rectangle in enumerate(parsed_rectangles):
        if not isinstance(rectangle, dict):
            violations.append({"type": "rectangle_format", "index": index + 1})
            continue
        raw_clue = rectangle.get("clue_cell")
        try:
            clue_cell = format_cell(*parse_cell(str(raw_clue)))
            top, left, bottom, right = _rectangle_bounds(rectangle)
        except (KeyError, TypeError, ValueError):
            violations.append({"type": "rectangle_format", "index": index + 1, "rectangle": rectangle})
            continue
        if clue_cell not in clue_positions:
            violations.append({"type": "unknown_clue", "index": index + 1, "clue_cell": clue_cell})
        if clue_cell in seen_clues:
            violations.append(
                {
                    "type": "duplicate_clue_rectangle",
                    "clue_cell": clue_cell,
                    "indices": [seen_clues[clue_cell], index + 1],
                }
            )
        else:
            seen_clues[clue_cell] = index + 1
        if top > bottom or left > right:
            violations.append({"type": "rectangle_order", "index": index + 1})
            continue
        if not (0 <= top <= bottom < height and 0 <= left <= right < width):
            violations.append({"type": "rectangle_bounds", "index": index + 1})
            continue
        cells = _bounds_cells((top, left, bottom, right))
        area = len(cells)
        expected_area = clue_values.get(clue_cell)
        if area != expected_area:
            violations.append(
                {
                    "type": "rectangle_area",
                    "clue_cell": clue_cell,
                    "expected": expected_area,
                    "actual": area,
                }
            )
        if clue_positions.get(clue_cell) not in cells:
            violations.append({"type": "clue_outside_rectangle", "clue_cell": clue_cell})
        contained_clues = sorted(
            (cell for cell, position in clue_positions.items() if position in cells),
            key=_cell_sort_key,
        )
        if contained_clues != [clue_cell]:
            violations.append(
                {
                    "type": "numbered_cell_count",
                    "clue_cell": clue_cell,
                    "contained_clues": contained_clues,
                }
            )
        for cell in cells:
            if cell in occupied:
                violations.append(
                    {
                        "type": "rectangle_overlap",
                        "cell": format_cell(*cell),
                        "clues": [occupied[cell], clue_cell],
                    }
                )
            else:
                occupied[cell] = clue_cell

    missing_clues = sorted(set(clue_positions) - set(seen_clues), key=_cell_sort_key)
    if missing_clues:
        violations.append({"type": "missing_clue_rectangles", "clue_cells": missing_clues})
    expected_cells = {(row, col) for row in range(height) for col in range(width)}
    missing_cells = sorted(expected_cells - set(occupied))
    if missing_cells:
        violations.append(
            {"type": "uncovered_cells", "cells": [format_cell(*cell) for cell in missing_cells]}
        )
    return violations


def _region_grid(
    height: int,
    width: int,
    rectangles: list[dict[str, Any]],
) -> list[list[str]]:
    grid = [["?" for _ in range(width)] for _ in range(height)]
    for rectangle in rectangles:
        try:
            top, left, bottom, right = _rectangle_bounds(rectangle)
            clue_cell = format_cell(*parse_cell(str(rectangle["clue_cell"])))
        except (KeyError, TypeError, ValueError):
            continue
        for row in range(max(0, top), min(height - 1, bottom) + 1):
            for col in range(max(0, left), min(width - 1, right) + 1):
                grid[row][col] = clue_cell
    return grid


def render_shikaku(
    height: int,
    width: int,
    clues: list[dict[str, Any]],
    rectangles: list[dict[str, Any]] | str | None = None,
) -> str:
    """Render the clue grid and, when supplied, rectangle ownership."""

    values: dict[Cell, list[str]] = {}
    for clue in clues:
        if not isinstance(clue, dict):
            continue
        try:
            cell = parse_cell(str(clue.get("cell")))
        except ValueError:
            continue
        values.setdefault(cell, []).append(str(clue.get("value", "?")))
    lines = [f"Shikaku {height}x{width}", "Clue grid (. = empty):"]
    for row in range(height):
        lines.append(
            " ".join("/".join(values.get((row, col), [])) or "." for col in range(width))
        )
    parsed_rectangles = _coerce_rectangles(rectangles) if rectangles is not None else None
    if parsed_rectangles is not None:
        lines.append("Rectangle ownership (each label is its clue cell):")
        lines.extend(" ".join(row) for row in _region_grid(height, width, parsed_rectangles))
    lines.append(
        "Rule: divide the entire grid into non-overlapping rectangles; each rectangle "
        "contains exactly one clue and its area equals that clue."
    )
    return "\n".join(lines)


def _solution_string(rectangles: list[dict[str, Any]]) -> str:
    normalized = [
        {
            "clue_cell": format_cell(*parse_cell(str(rectangle["clue_cell"]))),
            "top_left": format_cell(*parse_cell(str(rectangle["top_left"]))),
            "bottom_right": format_cell(*parse_cell(str(rectangle["bottom_right"]))),
        }
        for rectangle in rectangles
    ]
    normalized.sort(key=lambda rectangle: _cell_sort_key(rectangle["clue_cell"]))
    return json.dumps(normalized, separators=(",", ":"), sort_keys=True)


def _rectangle_evaluation(
    rectangle: dict[str, Any],
    clues: list[dict[str, Any]],
) -> dict[str, Any]:
    clue_values = {str(clue["cell"]): clue["value"] for clue in clues}
    clue_positions = {str(clue["cell"]): parse_cell(str(clue["cell"])) for clue in clues}
    clue_cell = str(rectangle["clue_cell"])
    bounds = _rectangle_bounds(rectangle)
    cells = _bounds_cells(bounds)
    contained = sorted(
        (cell for cell, position in clue_positions.items() if position in cells),
        key=_cell_sort_key,
    )
    area = len(cells)
    expected = clue_values.get(clue_cell)
    return {
        **rectangle,
        "area": area,
        "expected_area": expected,
        "contains_clue": clue_positions.get(clue_cell) in cells,
        "contained_clues": contained,
        "satisfied": area == expected and contained == [clue_cell],
    }


def _forced_ownership(
    height: int,
    width: int,
    candidates: dict[str, list[Rectangle]],
    solutions: list[list[Rectangle]],
) -> list[dict[str, str]]:
    if not solutions:
        return []
    possible_owners: dict[Cell, set[str]] = {
        (row, col): set() for row in range(height) for col in range(width)
    }
    in_every_candidate: dict[str, set[Cell]] = {}
    for clue_cell, rectangles in candidates.items():
        cell_sets = [_bounds_cells(_rectangle_bounds(rectangle)) for rectangle in rectangles]
        for cells in cell_sets:
            for cell in cells:
                possible_owners[cell].add(clue_cell)
        if cell_sets:
            in_every_candidate[clue_cell] = set.intersection(*(set(cells) for cells in cell_sets))

    forced: dict[Cell, tuple[str, str]] = {}
    for clue_cell, cells in in_every_candidate.items():
        for cell in cells:
            forced[cell] = (clue_cell, "in_every_rectangle_candidate")
    for cell, owners in possible_owners.items():
        if len(owners) == 1:
            clue_cell = next(iter(owners))
            forced[cell] = (clue_cell, "only_possible_owner")

    # Once the two-solution search has proved uniqueness, every ownership in the
    # sole tiling is forced, including deductions that require global exact-cover
    # interaction rather than a local candidate intersection.
    if len(solutions) == 1:
        for rectangle in solutions[0]:
            clue_cell = rectangle["clue_cell"]
            for cell in _bounds_cells(_rectangle_bounds(rectangle)):
                forced.setdefault(cell, (clue_cell, "unique_solution_ownership"))
    return [
        {"cell": format_cell(*cell), "clue_cell": owner, "reason": reason}
        for cell, (owner, reason) in sorted(forced.items())
    ]


def build_ground_truth(
    height: int,
    width: int,
    clues: list[dict[str, Any]],
    solution: str | list[dict[str, Any]],
    *,
    edge_case_kind: str | None = None,
    _solutions: list[list[Rectangle]] | None = None,
) -> dict[str, Any]:
    structural = validate_structure(height, width, clues)
    solutions = (
        _solutions
        if _solutions is not None
        else solve_shikaku(height, width, clues, limit=2) if not structural else []
    )
    if structural:
        validity_status, solvability_status = "invalid", "unknown"
    elif not solutions:
        validity_status, solvability_status = "valid", "unsolvable"
    elif len(solutions) == 1:
        validity_status, solvability_status = "valid", "unique"
    else:
        validity_status, solvability_status = "valid", "ambiguous"
    if edge_case_kind == "malformed_input":
        validity_status, solvability_status = "malformed", "unknown"

    selected = _coerce_rectangles(solution)
    if selected is None:
        selected = solutions[0] if solutions else []
    selected = [dict(rectangle) for rectangle in selected if isinstance(rectangle, dict)]
    solution_text = _solution_string(selected) if selected else "[]"
    candidate_map = rectangle_candidates(height, width, clues) if not structural else {}
    assert isinstance(candidate_map, dict)
    selected_by_clue = {
        str(rectangle.get("clue_cell")): rectangle for rectangle in selected
    }
    clue_evaluations = []
    for clue in clues:
        if not isinstance(clue, dict):
            continue
        cell = str(clue.get("cell"))
        rectangle = selected_by_clue.get(cell)
        evaluation = _rectangle_evaluation(rectangle, clues) if rectangle else None
        clue_evaluations.append(
            {
                "clue_cell": cell,
                "value": clue.get("value"),
                "candidate_count": len(candidate_map.get(cell, [])),
                "solution_rectangle": rectangle,
                "satisfied": bool(evaluation and evaluation["satisfied"]),
            }
        )
    rectangle_evaluations = []
    if not structural:
        for rectangle in selected:
            try:
                rectangle_evaluations.append(_rectangle_evaluation(rectangle, clues))
            except (KeyError, TypeError, ValueError):
                rectangle_evaluations.append({"rectangle": rectangle, "satisfied": False})
    forced = _forced_ownership(height, width, candidate_map, solutions)

    suggested_move: dict[str, Any] | None = None
    if solvability_status == "unique":
        singletons = [
            (cell, rectangles[0])
            for cell, rectangles in candidate_map.items()
            if len(rectangles) == 1
        ]
        if singletons:
            _, rectangle = min(singletons, key=lambda item: _cell_sort_key(item[0]))
            suggested_move = {**rectangle, "reason": "only_rectangle_candidate"}
        elif selected:
            clue_cell = min(
                selected_by_clue,
                key=lambda cell: (len(candidate_map.get(cell, [])), _cell_sort_key(cell)),
            )
            suggested_move = {
                **selected_by_clue[clue_cell],
                "reason": "most_constrained_in_unique_solution",
            }

    valid_selected = solution_violations(height, width, clues, selected)
    return {
        "height": height,
        "width": width,
        "clues": clues,
        "solution": solution_text,
        "solution_rectangles": selected,
        "region_grid": _region_grid(height, width, selected),
        "solved_board": render_shikaku(height, width, clues, selected),
        "validity_status": validity_status,
        "solvability_status": solvability_status,
        "unique_solution_status": solvability_status == "unique",
        # Malformed input is deliberately not treated as a solver request even
        # though the retained canonical record remains parseable for storage.
        "solution_count": 0 if edge_case_kind == "malformed_input" else len(solutions),
        "structural_violations": structural,
        "solution_violations": valid_selected,
        "candidate_rectangles": candidate_map,
        "candidate_counts": {cell: len(values) for cell, values in candidate_map.items()},
        "clue_evaluations": clue_evaluations,
        "rectangle_evaluations": rectangle_evaluations,
        "forced_ownership": forced,
        "suggested_move": suggested_move,
    }


class ShikakuPuzzleManager:
    """Deterministic, persistent Shikaku puzzle source for the dataset pipeline."""

    def __init__(self, config: dict[str, Any]):
        self.config = config
        output_path = Path(config["output_path"])
        puzzle_config = config.get("puzzles", {})
        self.bank_path = output_path / puzzle_config.get(
            "persistent_bank_filename", "shikaku_puzzle_bank.jsonl"
        )
        self.usage_path = output_path / puzzle_config.get(
            "usage_stats_filename", "shikaku_puzzle_usage.json"
        )
        self.seed = int(config.get("generation", {}).get("random_seed", 17))
        self._lineage_cache: dict[tuple[str, int], PuzzleRecord] = {}
        self.base_bank = self._build_base_bank()
        self._ensure_bank()
        self.usage_stats = self._load_usage_stats()

    def select_puzzle(self, scenario: Scenario, sample_index: int) -> PuzzleRecord:
        difficulty = scenario.difficulty if scenario.difficulty in _DIFFICULTY_SPECS else "easy"
        parent = self._lineage_record(difficulty, max(0, sample_index) // len(_TRANSFORMATIONS))
        if scenario.edge_case == "malformed_input":
            return self._malformed_variant(parent, sample_index)
        if scenario.edge_case == "invalid_clues":
            return self._fixture_variant(
                parent,
                sample_index,
                [{"cell": "r1c1", "value": 2}, {"cell": "r1c1", "value": 2}],
                "invalid_clues",
            )
        if scenario.edge_case == "unsolvable_puzzle":
            return self._fixture_variant(
                parent,
                sample_index,
                [{"cell": "r1c1", "value": 3}, {"cell": "r2c2", "value": 1}],
                "unsolvable_puzzle",
            )
        if scenario.edge_case == "ambiguous_puzzle":
            return self._fixture_variant(
                parent,
                sample_index,
                [{"cell": "r1c1", "value": 2}, {"cell": "r2c2", "value": 2}],
                "ambiguous_puzzle",
            )
        operation = _TRANSFORMATIONS[sample_index % len(_TRANSFORMATIONS)]
        return self._transformed_variant(parent, operation)

    def mark_used(self, puzzle: PuzzleRecord) -> None:
        for key in {puzzle.puzzle_id, puzzle.parent_puzzle_id or puzzle.puzzle_id}:
            self.usage_stats[key] = self.usage_stats.get(key, 0) + 1
        self.usage_path.parent.mkdir(parents=True, exist_ok=True)
        self.usage_path.write_text(
            json.dumps(self.usage_stats, indent=2, sort_keys=True), encoding="utf-8"
        )

    def _build_base_bank(self) -> list[PuzzleRecord]:
        records = []
        for difficulty in _DIFFICULTY_SPECS:
            record = self._generate_lineage(difficulty, 0)
            self._lineage_cache[(difficulty, 0)] = record
            records.append(record)
        return records

    def _lineage_record(self, difficulty: str, lineage: int) -> PuzzleRecord:
        key = (difficulty, lineage)
        if key not in self._lineage_cache:
            self._lineage_cache[key] = self._generate_lineage(difficulty, lineage)
        return self._lineage_cache[key]

    def _generate_lineage(self, difficulty: str, lineage: int) -> PuzzleRecord:
        height, width, rectangle_count, strategies = _DIFFICULTY_SPECS[difficulty]
        difficulty_offset = list(_DIFFICULTY_SPECS).index(difficulty) + 1
        rng = random.Random(
            self.seed * 1_000_003 + difficulty_offset * 100_019 + lineage * 7_919
        )
        for attempt in range(1_000):
            partitions = _guillotine_partition(height, width, rectangle_count, rng)
            clues = _clues_for_partition(partitions, rng)
            solutions = solve_shikaku(height, width, clues, limit=2)
            if len(solutions) != 1:
                continue
            lineage_id = f"shikaku_{difficulty}_{height}x{width}_lineage_{lineage}"
            signature = hashlib.sha1(canonical_puzzle(height, width, clues).encode()).hexdigest()[:16]
            return self._record(
                puzzle_id=lineage_id,
                height=height,
                width=width,
                clues=clues,
                solution_rectangles=solutions[0],
                difficulty=difficulty,
                strategies=strategies,
                parent_id=None,
                transformation="identity",
                source="generated",
                canonical_signature=signature,
                _solutions=solutions,
            )
        raise RuntimeError(
            f"Unable to generate a unique {difficulty} Shikaku lineage {lineage} after 1000 attempts."
        )

    def _transformed_variant(self, parent: PuzzleRecord, operation: str) -> PuzzleRecord:
        height, width, clues = parse_puzzle(parent.puzzle)
        new_height, new_width, transform = _coordinate_transform(height, width, operation)
        transformed_clues = [
            {
                "cell": format_cell(*transform(*parse_cell(str(clue["cell"])))),
                "value": clue["value"],
            }
            for clue in clues
        ]
        parent_rectangles = _coerce_rectangles(parent.solution) or []
        transformed_rectangles = [
            _transform_rectangle(rectangle, transform) for rectangle in parent_rectangles
        ]
        puzzle = canonical_puzzle(new_height, new_width, transformed_clues)
        return self._record(
            puzzle_id=self._variant_id(parent, operation, puzzle),
            height=new_height,
            width=new_width,
            clues=transformed_clues,
            solution_rectangles=transformed_rectangles,
            difficulty=parent.difficulty,
            strategies=list(parent.required_strategies),
            parent_id=parent.puzzle_id,
            transformation=operation,
            source=parent.source,
            canonical_signature=parent.canonical_signature,
        )

    def _malformed_variant(self, parent: PuzzleRecord, sample_index: int) -> PuzzleRecord:
        height, width, clues = parse_puzzle(parent.puzzle)
        rectangles = _coerce_rectangles(parent.solution) or []
        broken_boards = (
            "Shikaku grid: [5 x ? | clues={r1c1: 4, broken",
            "Shikaku ?x?: r1c1=6; rectangle data missing ]",
            "Shikaku clues: (r2c3 => ???, r4c1 => 3",
        )
        transformation = f"malformed_{sample_index}"
        return self._record(
            puzzle_id=self._variant_id(parent, transformation, parent.puzzle),
            height=height,
            width=width,
            clues=clues,
            solution_rectangles=rectangles,
            difficulty=parent.difficulty,
            strategies=list(parent.required_strategies),
            parent_id=parent.puzzle_id,
            transformation=transformation,
            source=parent.source,
            canonical_signature=parent.canonical_signature,
            edge_case_kind="malformed_input",
            rendered_board=broken_boards[sample_index % len(broken_boards)],
        )

    def _fixture_variant(
        self,
        parent: PuzzleRecord,
        sample_index: int,
        clues: list[dict[str, Any]],
        kind: str,
    ) -> PuzzleRecord:
        transformation = f"{kind}_{sample_index}"
        puzzle = canonical_puzzle(2, 2, clues)
        structural = validate_structure(2, 2, clues)
        solutions = solve_shikaku(2, 2, clues, limit=2) if not structural else []
        return self._record(
            puzzle_id=self._variant_id(parent, transformation, puzzle),
            height=2,
            width=2,
            clues=clues,
            solution_rectangles=solutions[0] if solutions else [],
            difficulty=parent.difficulty,
            strategies=list(parent.required_strategies),
            parent_id=parent.puzzle_id,
            transformation=transformation,
            source=parent.source,
            canonical_signature=parent.canonical_signature,
            edge_case_kind=kind,
            _solutions=solutions,
        )

    def _record(
        self,
        *,
        puzzle_id: str,
        height: int,
        width: int,
        clues: list[dict[str, Any]],
        solution_rectangles: list[dict[str, Any]],
        difficulty: str,
        strategies: list[str],
        parent_id: str | None,
        transformation: str,
        source: str,
        canonical_signature: str,
        edge_case_kind: str | None = None,
        rendered_board: str | None = None,
        _solutions: list[list[Rectangle]] | None = None,
    ) -> PuzzleRecord:
        clues = _normalized_clues(clues)
        puzzle = canonical_puzzle(height, width, clues)
        solution = _solution_string(solution_rectangles) if solution_rectangles else "[]"
        truth = build_ground_truth(
            height,
            width,
            clues,
            solution,
            edge_case_kind=edge_case_kind,
            _solutions=_solutions,
        )
        usage_stats = getattr(self, "usage_stats", {})
        return PuzzleRecord(
            puzzle_id=puzzle_id,
            puzzle=puzzle,
            solution=solution,
            difficulty=difficulty,
            num_clues=len(clues),
            required_strategies=list(strategies),
            unique_solution_status=truth["unique_solution_status"],
            source=source,
            canonical_signature=canonical_signature,
            usage_count=usage_stats.get(puzzle_id, 0),
            parent_puzzle_id=parent_id,
            transformation=transformation,
            rendered_board=rendered_board or render_shikaku(height, width, clues),
            ground_truth=truth,
            metadata={
                "height": height,
                "width": width,
                "clues": clues,
                **({"edge_case_kind": edge_case_kind} if edge_case_kind else {}),
            },
        )

    @staticmethod
    def _variant_id(parent: PuzzleRecord, transformation: str, puzzle: str) -> str:
        return hashlib.sha1(
            f"{parent.puzzle_id}|{transformation}|{puzzle}".encode()
        ).hexdigest()[:16]

    def _ensure_bank(self) -> None:
        if self.bank_path.exists():
            return
        self.bank_path.parent.mkdir(parents=True, exist_ok=True)
        with self.bank_path.open("w", encoding="utf-8") as handle:
            for puzzle in self.base_bank:
                handle.write(json.dumps(puzzle.to_dict(), ensure_ascii=False) + "\n")

    def _load_usage_stats(self) -> dict[str, int]:
        if not self.usage_path.exists():
            return {}
        return json.loads(self.usage_path.read_text(encoding="utf-8"))


def _guillotine_partition(
    height: int,
    width: int,
    rectangle_count: int,
    rng: random.Random,
) -> list[Bounds]:
    rectangles: list[Bounds] = [(0, 0, height - 1, width - 1)]
    while len(rectangles) < rectangle_count:
        splittable = [
            (index, bounds)
            for index, bounds in enumerate(rectangles)
            if bounds[2] > bounds[0] or bounds[3] > bounds[1]
        ]
        if not splittable:
            raise RuntimeError("Unable to split the Shikaku grid into the requested rectangles.")

        # Prefer a larger leaf but retain enough randomness to create genuinely
        # different sample-indexed lineages.
        weighted: list[tuple[int, Bounds]] = []
        for item in splittable:
            top, left, bottom, right = item[1]
            area = (bottom - top + 1) * (right - left + 1)
            weighted.extend([item] * max(1, area))
        index, (top, left, bottom, right) = rng.choice(weighted)
        options: list[tuple[Bounds, Bounds]] = []
        for cut in range(top, bottom):
            options.append(((top, left, cut, right), (cut + 1, left, bottom, right)))
        for cut in range(left, right):
            options.append(((top, left, bottom, cut), (top, cut + 1, bottom, right)))
        first, second = rng.choice(options)
        rectangles[index : index + 1] = [first, second]
    return sorted(rectangles)


def _clues_for_partition(partitions: list[Bounds], rng: random.Random) -> list[dict[str, Any]]:
    clues = []
    for top, left, bottom, right in partitions:
        cells = [
            (row, col)
            for row in range(top, bottom + 1)
            for col in range(left, right + 1)
        ]
        row, col = rng.choice(cells)
        clues.append(
            {
                "cell": format_cell(row, col),
                "value": (bottom - top + 1) * (right - left + 1),
            }
        )
    return _normalized_clues(clues)


def _coordinate_transform(
    height: int,
    width: int,
    operation: str,
) -> tuple[int, int, Callable[[int, int], Cell]]:
    transforms: dict[str, tuple[int, int, Callable[[int, int], Cell]]] = {
        "identity": (height, width, lambda row, col: (row, col)),
        "rotate_90": (width, height, lambda row, col: (col, height - 1 - row)),
        "rotate_180": (
            height,
            width,
            lambda row, col: (height - 1 - row, width - 1 - col),
        ),
        "rotate_270": (width, height, lambda row, col: (width - 1 - col, row)),
        "reflect_horizontal": (height, width, lambda row, col: (height - 1 - row, col)),
        "reflect_vertical": (height, width, lambda row, col: (row, width - 1 - col)),
        "transpose": (width, height, lambda row, col: (col, row)),
        "anti_transpose": (
            width,
            height,
            lambda row, col: (width - 1 - col, height - 1 - row),
        ),
    }
    if operation not in transforms:
        raise ValueError(f"Unknown Shikaku transformation: {operation}")
    return transforms[operation]


def _transform_rectangle(
    rectangle: dict[str, Any],
    transform: Callable[[int, int], Cell],
) -> Rectangle:
    top, left, bottom, right = _rectangle_bounds(rectangle)
    corners = [
        transform(top, left),
        transform(top, right),
        transform(bottom, left),
        transform(bottom, right),
    ]
    rows = [row for row, _ in corners]
    columns = [col for _, col in corners]
    clue_cell = format_cell(*transform(*parse_cell(str(rectangle["clue_cell"]))))
    return _rectangle(min(rows), min(columns), max(rows), max(columns), clue_cell)
